### ISSUE TITLE
Gerenciamento de tarefas

### ISSUE THREAD

**Issue by Lrisisger** [Lrisisger/LRISisger#1]
Criação de tarefas basicas. Elementos básicos para criação são: títulos da tarefa, quem é encarregador por faze-la, data criação, status (em andamento, feita, atrasada, agendada), data limite, descrição e observações.

OBS.: Faça primeiro os fluxogramas para que depois disso possa ser devidamente implementado.

**Comment by lucaseduardo76** [comment]
Segue fluxograma

[Fluxo gerenciamento de tarefas.pdf](https://github.com/Lrisisger/LRISisger/files/12642104/Fluxo.gerenciamento.de.tarefas.pdf)
