### ISSUE TITLE
Login de usuário

### ISSUE THREAD

**Issue by Lrisisger** [Lrisisger/LRISisger#2]
Login de usuário basico com verificação usuário e senha e o nível de acesso do usuário (Colaborador ou Moderador). Nenhum dos dois existam, retorne o erro genérico "Usuário ou senha incorreto(s)." Mantenha o tratamento de erros.

OBS.: Faça antes o fluxograma do processo para depois ser implementado.

**Comment by lucaseduardo76** [comment]
Segue fluxograma

[Fluxo Login.pdf](https://github.com/Lrisisger/LRISisger/files/12642103/Fluxo.Login.pdf)
