### ISSUE TITLE
Cadastro de Usuários e Moderadores

### ISSUE THREAD

**Issue by Lrisisger** [Lrisisger/LRISisger#3]
Montar uma lógica basica de cadastro de usuários/colaboradores e moderadores. O cadastro é sempre feito pelo ADM.
O mesmo deve ter tratamento de erros, confirmação basica de senha, verificação se o nome de usuário e email existe já foram usados ou não, também a definição basica de nível de acesso (Colaborador ou moderador).

OBS.: faça inicialmente o fluxograma da funcionalidade para fins de testes especificos antes do mesmo ser devidamente implementado como funcionalidade da aplicação.

**Comment by Lrisisger** [comment]
Segue o fluxograma
[Cadastro de usuários e moderadores.pdf](https://github.com/Lrisisger/LRISisger/files/12641618/Cadastro.de.usuarios.e.moderadores.pdf)

**Comment by luisaraujoc** [comment]
Segue o fluxograma
[Cadastro de usuários e moderadores.pdf](https://github.com/Lrisisger/LRISisger/files/12641628/Cadastro.de.usuarios.e.moderadores.pdf)

**Comment by lucaseduardo76** [comment]
Segue fluxograma atualizado

[Fluxo Cadastro.pdf](https://github.com/Lrisisger/LRISisger/files/12642102/Fluxo.Cadastro.pdf)
